// ─── Bộ tiêu chuẩn TT04/2025: kiểm định CHƯƠNG TRÌNH ĐÀO TẠO ────────────────
// Bóc từ nguyên văn Thông tư 04/2025/TT-BGDĐT, Chương II, Điều 4 đến Điều 11.
// Nguồn: kiem-dinh-chat-luong/new/tt04-kdcl-p001-030.md và các tệp cùng bộ.
//
// Vì sao cần tệp này: trước đây MỌI đợt kiểm định đều chạy trên bộ 15 tiêu
// chuẩn 60 tiêu chí của TT20, tức khung dành cho CƠ SỞ GIÁO DỤC. Ba đợt
// chương trình đào tạo vì thế gắn minh chứng vào những địa chỉ không tồn tại
// trong khung của mình, ví dụ tiêu chí 9.1 hay 11.1.
//
// Quy mô: 8 tiêu chuẩn, 52 tiêu chí, phân rã 6 · 7 · 5 · 7 · 8 · 6 · 8 · 5.
// Hai chỗ lệch đã đối chiếu và chốt theo nguyên văn thông tư:
//  · Bản tóm tắt kèm bộ tài liệu ghi "51 tiêu chí" ở dòng tiêu đề nhưng phần
//    liệt kê của chính nó cộng ra 52; đếm trên nguyên văn ra đúng 52.
//  · Trang giới thiệu trong phần mềm đang ghi phân rã 6 · 7 · 5 · 7 · 8 · 5 ·
//    6 · 8, tức đảo số tiêu chí của ba tiêu chuẩn cuối. Bản này theo thông tư.
//
// dieu_kien = tiêu chí ĐIỀU KIỆN: chỉ cần MỘT tiêu chí điều kiện không đạt thì
// cả tiêu chuẩn đó không đạt, dù các tiêu chí khác đều đạt.
const STANDARDS_TT04 = [
  { id: 1, name: "Mục tiêu và chuẩn đầu ra của chương trình đào tạo", criteria: [
    { code: "1.1", short: "Mục tiêu của chương trình đào tạo được xác định rõ ràng",
      full: "Mục tiêu của chương trình đào tạo được xác định rõ ràng, phù hợp và gắn kết với sứ mạng, tầm nhìn, chiến lược phát triển của cơ sở đào tạo; phù hợp với mục tiêu của giáo dục đại học theo quy định tại Luật Giáo dục đại học.",
      dieu_kien: false },
    { code: "1.2", short: "Chuẩn đầu ra của chương trình đào tạo được xây dựng rõ ràng",
      full: "Chuẩn đầu ra của chương trình đào tạo được xây dựng rõ ràng; phù hợp với sứ mạng, tầm nhìn và mục tiêu chiến lược của cơ sở đào tạo và được phổ biến đến các bên liên quan.",
      dieu_kien: false },
    { code: "1.3", short: "Chuẩn đầu ra của chương trình đào tạo phù hợp với Khung trình độ…",
      full: "Chuẩn đầu ra của chương trình đào tạo phù hợp với Khung trình độ quốc gia Việt Nam và chuẩn chương trình đào tạo nhóm ngành, bao gồm chuẩn đầu ra chung và chuẩn đầu ra chuyên biệt.",
      dieu_kien: true },
    { code: "1.4", short: "Chuẩn đầu ra của tất cả các học phần được xây dựng phải phù hợp…",
      full: "Chuẩn đầu ra của tất cả các học phần được xây dựng phải phù hợp và tương thích với chuẩn đầu ra của chương trình đào tạo đã công bố.",
      dieu_kien: false },
    { code: "1.5", short: "Chuẩn đầu ra của chương trình đào tạo phản ánh rõ yêu cầu của cá…",
      full: "Chuẩn đầu ra của chương trình đào tạo phản ánh rõ yêu cầu của các bên liên quan, đặc biệt là các bên liên quan bên ngoài.",
      dieu_kien: false },
    { code: "1.6", short: "Chuẩn đầu ra của chương trình đào tạo được đo lường đánh giá tại…",
      full: "Chuẩn đầu ra của chương trình đào tạo được đo lường đánh giá tại thời điểm người học tốt nghiệp.",
      dieu_kien: true },
  ] },
  { id: 2, name: "Cấu trúc và nội dung chương trình đào tạo", criteria: [
    { code: "2.1", short: "Bản mô tả chương trình đào tạo và đề cương các học phần có đủ th…",
      full: "Bản mô tả chương trình đào tạo và đề cương các học phần có đủ thông tin, được cập nhật, được phê duyệt và được công bố công khai để các bên liên quan dễ dàng tiếp cận.",
      dieu_kien: false },
    { code: "2.2", short: "Cấu trúc và nội dung của chương trình đào tạo được thiết kế và p…",
      full: "Cấu trúc và nội dung của chương trình đào tạo được thiết kế và phát triển để bảo đảm người học đạt được chuẩn đầu ra và có khối lượng học tập phù hợp với quy định.",
      dieu_kien: true },
    { code: "2.3", short: "Cấu trúc và nội dung của chương trình đào tạo được thiết kế và p…",
      full: "Cấu trúc và nội dung của chương trình đào tạo được thiết kế và phát triển dựa trên phản hồi và nhu cầu của các bên liên quan, đặc biệt là các bên liên quan bên ngoài.",
      dieu_kien: false },
    { code: "2.4", short: "Đóng góp của từng học phần trong việc đạt được chuẩn đầu ra của…",
      full: "Đóng góp của từng học phần trong việc đạt được chuẩn đầu ra của chương trình đào tạo là rõ ràng.",
      dieu_kien: true },
    { code: "2.5", short: "Chương trình đào tạo có cấu trúc logic",
      full: "Chương trình đào tạo có cấu trúc logic, trình tự hợp lý, có tính linh hoạt và tích hợp.",
      dieu_kien: false },
    { code: "2.6", short: "Cấu trúc và nội dung của chương trình đào tạo thể hiện rõ các họ…",
      full: "Cấu trúc và nội dung của chương trình đào tạo thể hiện rõ các học phần bắt buộc, tự chọn, lý thuyết, thực hành, trải nghiệm, nghiên cứu khoa học, các thành phần chính yếu và bổ trợ; cho phép người học lựa chọn theo định hướng nghề nghiệp của bản thân.",
      dieu_kien: false },
    { code: "2.7", short: "Cấu trúc và nội dung của chương trình đào tạo được rà soát",
      full: "Cấu trúc và nội dung của chương trình đào tạo được rà soát, đánh giá và cải tiến chất lượng theo quy trình, quy định; bảo đảm tính cập nhật, đáp ứng yêu cầu của thị trường lao động.",
      dieu_kien: false },
  ] },
  { id: 3, name: "Hoạt động dạy và học", criteria: [
    { code: "3.1", short: "Triết lý giáo dục của cơ sở đào tạo được tuyên bố rõ ràng",
      full: "Triết lý giáo dục của cơ sở đào tạo được tuyên bố rõ ràng, được phổ biến đến các bên liên quan và được truyền tải vào các hoạt động dạy và học.",
      dieu_kien: false },
    { code: "3.2", short: "Hoạt động dạy và học được thiết kế tương thích với chuẩn đầu ra…",
      full: "Hoạt động dạy và học được thiết kế tương thích với chuẩn đầu ra của chương trình đào tạo.",
      dieu_kien: true },
    { code: "3.3", short: "Hoạt động dạy và học thể hiện việc học tập chủ động",
      full: "Hoạt động dạy và học thể hiện việc học tập chủ động, thúc đẩy việc học tập, hình thành và phát triển phương pháp học tập và khả năng học tập suốt đời của người học.",
      dieu_kien: false },
    { code: "3.4", short: "Hoạt động dạy và học thúc đẩy người học đưa ra ý tưởng mới",
      full: "Hoạt động dạy và học thúc đẩy người học đưa ra ý tưởng mới, sáng kiến, đổi mới sáng tạo và tinh thần khởi nghiệp.",
      dieu_kien: false },
    { code: "3.5", short: "Quá trình dạy và học được cải tiến thường xuyên để đáp ứng yêu c…",
      full: "Quá trình dạy và học được cải tiến thường xuyên để đáp ứng yêu cầu của thị trường lao động và thúc đẩy việc học tập, đáp ứng chuẩn đầu ra của chương trình đào tạo.",
      dieu_kien: false },
  ] },
  { id: 4, name: "Đánh giá kết quả học tập", criteria: [
    { code: "4.1", short: "Các phương pháp đánh giá kết quả học tập của người học đa dạng",
      full: "Các phương pháp đánh giá kết quả học tập của người học đa dạng, tương thích với chuẩn đầu ra của chương trình đào tạo.",
      dieu_kien: false },
    { code: "4.2", short: "Có các quy định rõ ràng về đánh giá kết quả học tập",
      full: "Có các quy định rõ ràng về đánh giá kết quả học tập, quy trình phúc khảo, được phổ biến đến người học và được triển khai thực hiện một cách nhất quán.",
      dieu_kien: false },
    { code: "4.3", short: "Các tiêu chuẩn và quy trình đánh giá kết quả học tập",
      full: "Các tiêu chuẩn và quy trình đánh giá kết quả học tập, xét công nhận kết quả học tập, xét tốt nghiệp được phổ biến đến người học và được triển khai thực hiện một cách nhất quán.",
      dieu_kien: false },
    { code: "4.4", short: "Các phương pháp đánh giá kết quả học tập được thể hiện qua ma tr…",
      full: "Các phương pháp đánh giá kết quả học tập được thể hiện qua ma trận, tiêu chí và mức độ đánh giá, đáp án, thang điểm chi tiết, kế hoạch đánh giá và các quy định cụ thể để bảo đảm độ giá trị, độ tin cậy và sự công bằng.",
      dieu_kien: false },
    { code: "4.5", short: "Các phương pháp đánh giá kết quả học tập bảo đảm đo lường được m…",
      full: "Các phương pháp đánh giá kết quả học tập bảo đảm đo lường được mức độ đạt chuẩn đầu ra của từng học phần và chuẩn đầu ra của chương trình đào tạo.",
      dieu_kien: true },
    { code: "4.6", short: "Kết quả đánh giá được phản hồi kịp thời cho người học để người h…",
      full: "Kết quả đánh giá được phản hồi kịp thời cho người học để người học cải thiện việc học tập, phương pháp học tập và kết quả học tập.",
      dieu_kien: false },
    { code: "4.7", short: "Việc đánh giá kết quả học tập và các quy định về đánh giá kết qu…",
      full: "Việc đánh giá kết quả học tập và các quy định về đánh giá kết quả học tập được định kỳ rà soát và cải tiến để bảo đảm đo lường được chuẩn đầu ra của chương trình đào tạo, đáp ứng nhu cầu của các bên liên quan.",
      dieu_kien: false },
  ] },
  { id: 5, name: "Đội ngũ giảng viên, nghiên cứu viên", criteria: [
    { code: "5.1", short: "Kế hoạch phát triển đội ngũ giảng viên",
      full: "Kế hoạch phát triển đội ngũ giảng viên, nghiên cứu viên tham gia chương trình đào tạo được thực hiện nhằm bảo đảm về số lượng và chất lượng đáp ứng các yêu cầu về đào tạo, nghiên cứu khoa học và kết nối phục vụ cộng đồng.",
      dieu_kien: false },
    { code: "5.2", short: "Số lượng và chất lượng đội ngũ giảng viên",
      full: "Số lượng và chất lượng đội ngũ giảng viên, nghiên cứu viên đáp ứng yêu cầu thực hiện chương trình đào tạo theo quy định; khối lượng công việc của đội ngũ giảng viên, nghiên cứu viên được đo lường, giám sát để cải tiến chất lượng đào tạo, nghiên cứu khoa học và kết nối phục vụ cộng đồng.",
      dieu_kien: true },
    { code: "5.3", short: "Năng lực của đội ngũ giảng viên",
      full: "Năng lực của đội ngũ giảng viên, nghiên cứu viên được xác định, được đánh giá và thông tin tới các bên có liên quan trực tiếp.",
      dieu_kien: false },
    { code: "5.4", short: "Giảng viên, nghiên cứu viên được phân công nhiệm vụ phù hợp với…",
      full: "Giảng viên, nghiên cứu viên được phân công nhiệm vụ phù hợp với trình độ, năng lực và kinh nghiệm.",
      dieu_kien: false },
    { code: "5.5", short: "Việc bổ nhiệm/thăng tiến của giảng viên",
      full: "Việc bổ nhiệm/thăng tiến của giảng viên, nghiên cứu viên dựa trên hệ thống đánh giá năng lực, kết quả giảng dạy, thực hiện nhiệm vụ nghiên cứu khoa học và kết nối phục vụ cộng đồng",
      dieu_kien: false },
    { code: "5.6", short: "Trách nhiệm, quyền hạn và nghĩa vụ của giảng viên",
      full: "Trách nhiệm, quyền hạn và nghĩa vụ của giảng viên, nghiên cứu viên được xác định rõ ràng theo quy định và được phổ biến để tất cả giảng viên, nghiên cứu viên hiểu rõ và thực hiện.",
      dieu_kien: false },
    { code: "5.7", short: "Nhu cầu về đào tạo, bồi dưỡng và phát triển chuyên môn của giảng…",
      full: "Nhu cầu về đào tạo, bồi dưỡng và phát triển chuyên môn của giảng viên, nghiên cứu viên được xác định có tính hệ thống; các hoạt động đào tạo, bồi dưỡng được triển khai để đáp ứng nhu cầu.",
      dieu_kien: false },
    { code: "5.8", short: "Công tác quản lý để đánh giá chất lượng giảng dạy",
      full: "Công tác quản lý để đánh giá chất lượng giảng dạy, nghiên cứu khoa học và phục vụ cộng đồng của giảng viên, nghiên cứu viên bao gồm cả việc khen thưởng và công nhận được triển khai theo quy định, quy trình cụ thể.",
      dieu_kien: false },
  ] },
  { id: 6, name: "Các dịch vụ hỗ trợ người học", criteria: [
    { code: "6.1", short: "Chính sách, tiêu chí và quy trình tuyển sinh được xác định rõ rà…",
      full: "Chính sách, tiêu chí và quy trình tuyển sinh được xác định rõ ràng theo yêu cầu của chương trình đào tạo; được công bố công khai và được cập nhật.",
      dieu_kien: true },
    { code: "6.2", short: "Năng lực của đội ngũ cung cấp dịch vụ hỗ trợ được xác định rõ rà…",
      full: "Năng lực của đội ngũ cung cấp dịch vụ hỗ trợ được xác định rõ ràng trong tiêu chuẩn của vị trí việc làm, tiêu chí tuyển dụng, trong phân công nhiệm vụ và được đánh giá để bảo đảm phù hợp với nhu cầu của các bên liên quan.",
      dieu_kien: false },
    { code: "6.3", short: "Kế hoạch ngắn hạn và dài hạn đối với dịch vụ hỗ trợ người học (h…",
      full: "Kế hoạch ngắn hạn và dài hạn đối với dịch vụ hỗ trợ người học (học thuật và phi học thuật) được xây dựng, triển khai thực hiện để bảo đảm đáp ứng đầy đủ và có chất lượng các dịch vụ hỗ trợ đào tạo, nghiên cứu khoa học và kết nối phục vụ cộng đồng.",
      dieu_kien: false },
    { code: "6.4", short: "Có hệ thống quản lý đào tạo phù hợp để giám sát",
      full: "Có hệ thống quản lý đào tạo phù hợp để giám sát, ghi nhận được tiến độ, kết quả học tập và khối lượng học tập của người học; việc phản hồi cho người học và hoạt động khắc phục bất cập được triển khai kịp thời và giúp người học cải thiện việc học tập.",
      dieu_kien: false },
    { code: "6.5", short: "Có các hoạt động tư vấn học tập",
      full: "Có các hoạt động tư vấn học tập, hoạt động ngoại khóa, các cuộc thi và các dịch vụ hỗ trợ khác để giúp cải thiện việc học tập và tăng khả năng có việc làm của người học.",
      dieu_kien: false },
    { code: "6.6", short: "Các dịch vụ hỗ trợ người học được định kỳ đánh giá",
      full: "Các dịch vụ hỗ trợ người học được định kỳ đánh giá, đối sánh và cải tiến chất lượng.",
      dieu_kien: false },
  ] },
  { id: 7, name: "Cơ sở hạ tầng, cơ sở vật chất và trang thiết bị", criteria: [
    { code: "7.1", short: "Có hệ thống phòng làm việc, phòng học và các phòng chức năng với…",
      full: "Có hệ thống phòng làm việc, phòng học và các phòng chức năng với các trang thiết bị phù hợp để triển khai chương trình đào tạo, hỗ trợ triển khai hoạt động đào tạo, nghiên cứu khoa học và kết nối phục vụ cộng đồng.",
      dieu_kien: false },
    { code: "7.2", short: "Các phòng thí nghiệm, phòng thực hành và trang thiết bị đầy đủ t…",
      full: "Các phòng thí nghiệm, phòng thực hành và trang thiết bị đầy đủ theo yêu cầu của chương trình đào tạo, được cập nhật, được sử dụng hiệu quả đáp ứng yêu cầu của người học, giảng viên và nghiên cứu viên.",
      dieu_kien: false },
    { code: "7.3", short: "Có thư viện, thư viện số và nguồn học liệu được cập nhật đáp ứng…",
      full: "Có thư viện, thư viện số và nguồn học liệu được cập nhật đáp ứng nhu cầu đào tạo, nghiên cứu khoa học, có cập nhật tiến bộ về công nghệ thông tin - truyền thông.",
      dieu_kien: true },
    { code: "7.4", short: "Có hệ thống công nghệ thông tin",
      full: "Có hệ thống công nghệ thông tin, hạ tầng mạng và máy tính dễ dàng tiếp cận và sử dụng, đáp ứng nhu cầu của người học, giảng viên, nghiên cứu viên, đội ngũ quản lý và nhân viên trong các hoạt động giảng dạy, nghiên cứu khoa học, kết nối phục vụ cộng đồng và quản lý hành chính.",
      dieu_kien: false },
    { code: "7.5", short: "Môi trường tâm lý, xã hội và cảnh quan thiên nhiên tạo thuận lợi…",
      full: "Môi trường tâm lý, xã hội và cảnh quan thiên nhiên tạo thuận lợi cho hoạt động đào tạo, nghiên cứu khoa học và sự thoải mái cho người học.",
      dieu_kien: false },
    { code: "7.6", short: "Các tiêu chuẩn về môi trường",
      full: "Các tiêu chuẩn về môi trường, sức khỏe, an toàn được xác định và triển khai có lưu ý đến các nhu cầu của các nhóm người học đặc thù, chuyên biệt (nếu có).",
      dieu_kien: false },
    { code: "7.7", short: "Năng lực đội ngũ hỗ trợ về cơ sở vật chất và trang thiết bị được…",
      full: "Năng lực đội ngũ hỗ trợ về cơ sở vật chất và trang thiết bị được xác định và được đánh giá đáp ứng nhu cầu các bên liên quan.",
      dieu_kien: false },
    { code: "7.8", short: "Chất lượng cơ sở vật chất phục vụ chương trình đào tạo được định…",
      full: "Chất lượng cơ sở vật chất phục vụ chương trình đào tạo được định kỳ đánh giá và cải tiến.",
      dieu_kien: false },
  ] },
  { id: 8, name: "Đầu ra và kết quả đầu ra", criteria: [
    { code: "8.1", short: "Tỉ lệ tốt nghiệp, thôi học và thời gian tốt nghiệp trung bình củ…",
      full: "Tỉ lệ tốt nghiệp, thôi học và thời gian tốt nghiệp trung bình của người học được xác lập, giám sát, đối sánh để cải tiến chất lượng.",
      dieu_kien: false },
    { code: "8.2", short: "Tỉ lệ việc làm bao gồm cả tự tạo việc làm",
      full: "Tỉ lệ việc làm bao gồm cả tự tạo việc làm, khởi nghiệp và học tập nâng cao trình độ của người học tốt nghiệp được xác lập, giám sát và đối sánh để cải tiến chất lượng.",
      dieu_kien: true },
    { code: "8.3", short: "Hoạt động nghiên cứu khoa học và sản phẩm sáng tạo",
      full: "Hoạt động nghiên cứu khoa học và sản phẩm sáng tạo, sáng chế của người học, giảng viên và nghiên cứu viên được xác lập, giám sát và đối sánh để cải tiến chất lượng.",
      dieu_kien: false },
    { code: "8.4", short: "Dữ liệu về mức độ người học đạt chuẩn đầu ra của chương trình đà…",
      full: "Dữ liệu về mức độ người học đạt chuẩn đầu ra của chương trình đào tạo được xác lập và giám sát để cải tiến chất lượng.",
      dieu_kien: false },
    { code: "8.5", short: "Mức độ hài lòng của các bên liên quan được xác lập",
      full: "Mức độ hài lòng của các bên liên quan được xác lập, giám sát, đối sánh để cải tiến chất lượng.",
      dieu_kien: false },
  ] },
];

module.exports = { STANDARDS_TT04 };
